### ISSUE TITLE
Future plans for this project

### ISSUE THREAD

**Issue by ialokim** [kiesel/hbcifacade#1]
I'm interested in this project and your corresponding AndroidBalance app. Are you still planning to work on these and would accept PR? Or would you be okay with me forking your two projects and working on them on my own?

**Comment by kiesel** [comment]
It is not much of a project, I would say. It was started as a side project but did not get anywhere.

I'd suggest rather starting from scratch, not using some of these. Maybe you need to look into the underlying library hbci4java...
